### ISSUE TITLE
태그 블럭 미작동

### ISSUE THREAD

**Issue by nnnlog** [HmHmmHm/TAGBlock#8]
태그 블럭 명령어 작동시에 추가됏다고 뜨는데 실제로는 블럭에 안떠요

**Comment by nnnlog** [comment]
@onebone @ZINGDING 확인 좀...

**Comment by Mintos74** [comment]
그리고 0.16 에서 호환자체가 안됩니다.

**Comment by nnnlog** [comment]
@Mintos74 호환이라는게 서버의 플러그인 호환인지, 맵에서의 호환인지 구분이 안되네요

**Comment by ghost** [comment]
@ParkChanSol @Mintos74 
0.15 부터 PM에서 엔티티를 없애서 호환이 안됩니다.
호환하려면 업데이트를 해야합니다.

**Comment by nnnlog** [comment]
@ZINGDING 업데이트 해주세요

어떤 엔티티를 기존에 사용했었나요?

**Comment by ghost** [comment]
@ParkChanSol 
시간될때 하겠습니다.

**Comment by nnnlog** [comment]
@ZINGDING 감사합니다

**Comment by angelless** [comment]
@ZINGDING 감사합니다

**Comment by ghost** [comment]
@angelless 
저분...

**Comment by nnnlog** [comment]
@ZINGDING @angelless 무슨 상황이지...?

**Comment by wsj7178** [comment]
@ZINGDING 

```
public function initPackets() {
        $this->packet ["AddEntityPacket"] = new AddPlayerPacket ();
        $this->packet ["AddEntityPacket"]->eid = 0;
        $this->packet ["AddEntityPacket"]->uuid = UUID::fromRandom();
        $this->packet ["AddEntityPacket"]->x = 0;
        $this->packet ["AddEntityPacket"]->y = 0;
        $this->packet ["AddEntityPacket"]->z = 0;
        $this->packet ["AddEntityPacket"]->speedX = 0;
        $this->packet ["AddEntityPacket"]->speedY = 0;
        $this->packet ["AddEntityPacket"]->speedZ = 0;
        $this->packet ["AddEntityPacket"]->yaw = 0;
        $this->packet ["AddEntityPacket"]->pitch = 0;
        $this->packet ["AddEntityPacket"]->item = Item::get(Item::AIR);
        $flag = 0;
        $flag |= 1 << Entity::DATA_FLAG_INVISIBLE;
        $flag |= 1 << Entity::DATA_FLAG_CAN_SHOW_NAMETAG;
        $flag |= 1 << Entity::DATA_FLAG_ALWAYS_SHOW_NAMETAG;
        $flag |= 1 << Entity::DATA_FLAG_IMMOBILE;

        $this->packet ["AddEntityPacket"]->metadata = [ 
                Entity::DATA_FLAGS => [ 
                        Entity::DATA_TYPE_LONG,
                        $flag
                ],
                Entity::DATA_NAMETAG => [ 
                        Entity::DATA_TYPE_STRING,
                        "" 
                ],
                Entity::DATA_LEAD_HOLDER_EID => [
                        Entity::DATA_TYPE_LONG,
                        -1
                ],
                Entity::DATA_FLAG_TAMED => [
                        Entity::DATA_TYPE_BYTE,
                        0
                ],
        ];

        $this->packet ["RemoveEntityPacket"] = new RemoveEntityPacket ();
    }
```

아까 제가 패킷만 일단 변경해봤는데 안뜨더라고요

**Comment by ghost** [comment]
@wsj7178 
헉 지금 봤네요 ((:3
제보 감사드림니당! :)

**Comment by nnnlog** [comment]
@XiangZhao969
That's error isn't related this bug.
그 오류는 이 버그와 상관이 없습니다

**Comment by ZINGDING** [comment]
@ParkChanSol 
저분 한국어 모르시는데...

**Comment by ghost** [comment]
@ParkChanSol 
문법 수정 했습니다.

**Comment by nnnlog** [comment]
@ZINGDING 무슨 문법요?

**Comment by Mintos74** [comment]
0.16 호환이 이제 되는건가요?

**Comment by ghost** [comment]
@Mintos74 아니요

**Comment by nnnlog** [comment]
@Mintos74 위에서 보시다시피 @ZINGDING 님께서 시간나실때 수정한다고 하셨습니다 :)

**Comment by Mintos74** [comment]
@ZINGDING 님 0.16 서버가 늘어나는데, 언제쯤 가능할까요? 많은 사람들이 불편을 겪고 있네요.

**Comment by nnnlog** [comment]
@Mintos74 이 것은 스팸입니다(깃허브 상), 더구나 @ZINGDING 님은 @organization 회원도 아니십니다.

**Comment by ghost** [comment]
@ParkChanSol  @organization 회원 맞는데요;;
회원 맞으니까 라벨도 달고 레포도 만들죠;;

**Comment by ghost** [comment]
@Mintos74 
시간이 비질 않네요 'ㅁ'...

**Comment by nnnlog** [comment]
@ZINGDING 근데 @organization 회원이라 안뜨는데요... maru 님이나 원본님은 뜨는데...

**Comment by ghost** [comment]
@ParkChanSol  잘 모르시는거 같아서 알려드리는데
깃허브 조직 회원이면 **private** 혹은 **public**으로 설정해서
조직 회원이 아닌 사람에게 자기가 조직에 해당하지 않는것처럼 보이게 할 수 있습니다.
**+** 깃허브 상태메시지 저랑 비슷하더라구요 ㅋ
![image](https://cloud.githubusercontent.com/assets/16650663/20140041/57fbac9a-a6cc-11e6-86f6-bc7c9e02fe4b.png)

**Comment by nnnlog** [comment]
@ZINGDING 그리고 HS-Team 에 텔레그램 채널에 들어가봤더니, 아무것도 없었다는...

**Comment by nnnlog** [comment]
@zicwoboo @wsj7178 

@solo5star 님(솔로) 말씀으로는 원래 플긴 구조가 0번(공기) 아이템 엔티티에다가 네임태그 달아서 패킷 보내는 방식 이라고 하셨는데, FloatingTextPaticle 으로 다시 구조를 짤 수 있다는 거 같은데, 전 모르겠습니다

**Comment by wsj7178** [comment]
@ParkChanSol 
제가 누킷에서 0.16 변환할땐
https://github.com/MCFT-Server/FloatingText/commit/5d951e7b25cca94b38ad3451db9edcacddacc87c
플레이어에 생성으로 엔티티 안보이게 작업햇는데 이건 네트워크 부분이라 PM에서도 똑같이 될줄 알았더니 안되더군요

**Comment by JellyBrick** [comment]
고쳤습니다.
